<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="InterfaceWatchDog">
      <HintPath>..\..\InterfaceWatchDog\bin\Debug\net8.0-windows\InterfaceWatchDog.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>